version: "3"

services:
  namenode:
    image: mfisser/hadoop-namenode:1.0.0-hadoop2.7.6-java8
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env

  resourcemanager:
    image: mfisser/hadoop-resourcemanager:1.0.0-hadoop2.7.6-java8
    container_name: resourcemanager
    depends_on:
      - namenode
      - datanode1
      - datanode2
    env_file:
      - ./hadoop-hive.env
  
  historyserver:
    image: mfisser/hadoop-historyserver:1.0.0-hadoop2.7.6-java8
    container_name: historyserver
    depends_on:
      - namenode
      - datanode1
      - datanode2
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop-hive.env
  
  nodemanager1:
    image: mfisser/hadoop-nodemanager:1.0.0-hadoop2.7.6-java8
    container_name: nodemanager1
    depends_on:
      - namenode
      - datanode1
      - datanode2
    env_file:
      - ./hadoop-hive.env

  nodemanager2:
    image: mfisser/hadoop-nodemanager:1.0.0-hadoop2.7.6-java8
    container_name: nodemanager2
    depends_on:
      - namenode
      - datanode1
      - datanode2
    env_file:
      - ./hadoop-hive.env      
  
  datanode1:
    image: mfisser/hadoop-datanode:1.0.0-hadoop2.7.6-java8
    container_name: datanode1
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env  

  datanode2:
    image: mfisser/hadoop-datanode:1.0.0-hadoop2.7.6-java8
    container_name: datanode2
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env     

  datanode3:
    image: mfisser/hadoop-datanode:1.0.0-hadoop2.7.6-java8
    container_name: datanode3
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env

  hive-server:
    image: mfisser/hive:1.0.0-hive2.3.2-for-postgresql-metastore 
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"

  hive-metastore:
    image: mfisser/hive:1.0.0-hive2.3.2-for-postgresql-metastore 
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode1:50075 datanode2:50075 datanode3:50075 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"

  hive-metastore-postgresql:
    image: mfisser/postgres:1.0.0-hive-for-postgresql-metastore
  
  impalad1:
    image: mfisser/impala-impalad:1.0.0
    depends_on:
      - statestore
    environment:
      - IMPALA_CATALOG_HOST=catalog
      - IMPALA_STATESTORE_HOST=statestore
      - METASTORE_HOST=hive-metastore
    ports:
      - 21000:21000
      - 21050:21050
      - 25000:25000

  impalad2:
    image: mfisser/impala-impalad:1.0.0
    depends_on:
      - statestore
    environment:
      - IMPALA_CATALOG_HOST=catalog
      - IMPALA_STATESTORE_HOST=statestore
      - METASTORE_HOST=hive-metastore
    ports:
      - 21001:21000
      - 21051:21050
      - 25001:25000
  catalog:
    image: mfisser/impala-catalog:1.0.0
    depends_on:
      - hive-metastore
    environment:
      - IMPALA_CATALOG_HOST=catalog
      - IMPALA_STATESTORE_HOST=statestore
      - METASTORE_HOST=hive-metastore
    ports:
      - 25020:25020      
  
  statestore:
    image: mfisser/impala-state-store:1.0.0
    depends_on:
      - catalog
    environment:
      - IMPALA_CATALOG_HOST=catalog
      - IMPALA_STATESTORE_HOST=statestore
      - METASTORE_HOST=hive-metastore
    ports:
      - 25010:25010          

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3:
  hadoop_historyserver:    